from typing import Protocol

from robot_ui.erosion_parameters import ErosionParameters


class RobotHardware(Protocol):
    def move_xyz(self, x: float, y: float, z: float) -> None: ...
    def move_joints(self, joints: list[float]) -> None: ...
    def set_erosion(self, enabled: bool) -> None: ...
    def set_water(self, enabled: bool) -> None: ...
    def toggle_pump_in(self) -> bool: ...
    def toggle_pump_out(self) -> bool: ...
    def run_erosion(self, file_path: str, params: ErosionParameters) -> None: ...
